version: '3.8'
services:
  web:
    image: odoo:17.0
    depends_on:
      - mydb
    ports:
      - "80:8069"
    volumes:
      - web-data:/var/lib/odoo
      - addons:/mnt/extra-addons
    environment:
      - HOST=mydb
      - USER=odoo
      - PASSWORD=myodoo
  mydb:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  web-data:
  db-data:
  addons:
